version: '3.8'



services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd-storage:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: [ 'CMD', 'etcdctl', 'endpoint', 'health' ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      bot_network:
        ipv4_address: ${ETCD_DOCKER_IP}

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ':9001' /data/
    ports:
      - ${MINIO_PORT_INTERNAL}:${MINIO_PORT}
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live' ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      bot_network:
        ipv4_address: ${MINIO_DOCKER_IP}


  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.5.0-beta
    command: [ 'milvus', 'run', 'standalone' ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:{MINIO_PORT}
    volumes:
      - milvus-storage:/var/lib/milvus
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:9091/healthz' ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - '19530:19530'
      - '9091:9091'
    depends_on:
      - 'etcd'
      - 'minio'
    networks:
      bot_network:
        ipv4_address: ${MILVUS_DOCKER_IP}


  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT_INTERNAL}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U cy' ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      bot_network:
        ipv4_address: ${DB_DOCKER_IP}


  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "${REDIS_PORT_INTERNAL}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      bot_network:
        ipv4_address: ${REDIS_DOCKER_IP}

  worker:
    build:
      context: ../
    command: celery --app package.celery.worker.celery worker --loglevel=info
    volumes:
      - celery_volume:/usr/src
    depends_on:
      - redis
    networks:
      bot_network:
        ipv4_address: ${WORKER_DOCKER_IP}

  dashboard:
    build: ../
    command: celery --broker=${CELERY_BROKER_URL} flower --port=5555
    ports:
      - ${DASHBOARD_PORT_INTERNAL}:${DASHBOARD_PORT}
    depends_on:
      - redis
      - worker
    networks:
      bot_network:
        ipv4_address: ${DASHBOARD_DOCKER_IP}

volumes:
  minio-storage:
  milvus-storage:
  etcd-storage:
  postgres-data:
  celery_volume:
  redis_data:

networks:
  bot_network:
    name: "botnet"
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"