"""Initial

Revision ID: 955512740d4b
Revises: 
Create Date: 2024-12-08 12:11:28.619582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '955512740d4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.BigInteger(), nullable=True),
    sa.Column('s3_briefly', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_id'), 'docs', ['id'], unique=False)
    op.create_table('milvus_docs',
    sa.Column('milvus_id', sa.Integer(), nullable=False),
    sa.Column('docs_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(), nullable=True),
    sa.ForeignKeyConstraint(['docs_id'], ['docs.id'], ),
    sa.PrimaryKeyConstraint('milvus_id', 'docs_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milvus_docs')
    op.drop_index(op.f('ix_docs_id'), table_name='docs')
    op.drop_table('docs')
    # ### end Alembic commands ###
