"""initial

Revision ID: c9309fddd1ae
Revises: 
Create Date: 2025-01-06 02:57:11.472461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import FetchedValue

# revision identifiers, used by Alembic.
revision: str = 'c9309fddd1ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('checksum', sa.BigInteger(), nullable=True),
                    sa.Column('s3_briefly', sa.String(length=255), nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(),
                              nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(),
                              nullable=True),
                    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(),
                              nullable=True),
                    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_docs_id'), 'docs', ['id'], unique=False)
    op.create_table('milvus_docs',
                    sa.Column('milvus_id', sa.BigInteger(), nullable=False),
                    sa.Column('docs_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(),
                              nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(),
                              nullable=True),
                    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), server_default=FetchedValue(),
                              nullable=True),
                    sa.ForeignKeyConstraint(['docs_id'], ['docs.id'], ),
                    sa.PrimaryKeyConstraint('milvus_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milvus_docs')
    op.drop_index(op.f('ix_docs_id'), table_name='docs')
    op.drop_table('docs')
    # ### end Alembic commands ###
